name = "Tears of the Craftom"
author = "DrgnFireYellow"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f053e4f27cf2a0a1bb637998b6edaa1fc3f8708225efbba7cc757c203cf2922c"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"
