name = "Tears of the Craftom"
author = "DrgnFireYellow"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1dbe5a148c77f7148e28ee05ca2734337abb1997a03497782b0803f7cb785b9"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"
